import type { FlowEdgeInput, FlowTurnInput } from "../../src/shared/flows";

/**
 * The T900-T1001 window of session S15069 - the "rebuild graph" every figure in
 * the flow-relations spec was measured on (spec.md, and the peer session's
 * per-round derivations at S21460/T93-T112).
 *
 * PROVENANCE, reproducible verbatim (read-only, never a write path):
 *
 *   sqlite3 -readonly ~/.claude-mnemo/claude-mnemo.db "
 *     with w as (select id, prompt_number from turns
 *                where session_id=15069 and prompt_number between 900 and 1001)
 *     select a.prompt_number, m.relation, b.prompt_number from memory_edges m
 *       join w a on a.id=m.citing_id and m.citing_kind='turn'
 *       join w b on b.id=m.cited_id and m.cited_kind='turn'
 *      where m.relation is not null and m.relation<>'supersedes';"
 *
 * Turn ids here are PROMPT NUMBERS (the T-addresses the spec and the peer notes
 * argue in), not row ids: the window's row ids are 12261-12412. Both endpoints
 * of every edge are inside the window - one further edge exists whose cited end
 * (T798) sits outside it and one evidence-for edge points INTO the window from a
 * later turn; both are dropped, which is why this fixture holds 113 edges where
 * the peer counted 114 in the wider frame. Neither can change a within-window
 * flow (T798 holds no window flow to inherit, and a citing turn outside the
 * window is not a window turn). 102 turns, 113 edges, 85 of the turns
 * edge-bearing - the universe the peer's "5 of 85 edged turns unassigned" is
 * measured over.
 *
 * Relation words are MECHANICALLY mapped to the eight-word vocabulary on the way
 * in (spec's migration step 1-2), which is why no narrows or collects edge
 * appears - both start empty:
 *
 *   refines(24)->extends . depends-on(52)->consume . encodes(27)->grounds
 *   grounded-on(8)->grounds . evidence-against(1)->refutes . override(1) unchanged
 *
 * Mapped totals: consume 52 . extends 24 . grounds 35 . override 1 . refutes 1.
 *
 * Frozen on 2026-08-21; every in-window stance edge predates the peer's
 * measurement (latest 2026-08-21 13:53, the session ran 17:53-21:00), so this is
 * the graph the spec's numbers were read off.
 */

export const FLOW_WINDOW_TURNS: readonly FlowTurnInput[] = [
  { id: 900, type: ["design", "ops"] },
  { id: 901, type: ["design"] },
  { id: 902, type: ["review"] },
  { id: 903, type: ["review"] },
  { id: 904, type: ["review"] },
  { id: 905, type: ["delegate"] },
  { id: 906, type: ["design"] },
  { id: 907, type: ["compact"] },
  { id: 908, type: [] },
  { id: 909, type: ["review"] },
  { id: 910, type: ["design"] },
  { id: 911, type: ["implement", "review"] },
  { id: 912, type: ["design"] },
  { id: 913, type: ["design"] },
  { id: 914, type: ["review", "discuss"] },
  { id: 915, type: ["measure", "correction"] },
  { id: 916, type: ["measure"] },
  { id: 917, type: [] },
  { id: 918, type: ["review"] },
  { id: 919, type: ["design"] },
  { id: 920, type: ["design"] },
  { id: 921, type: ["design"] },
  { id: 922, type: ["discuss"] },
  { id: 923, type: ["delegate"] },
  { id: 924, type: ["review"] },
  { id: 925, type: ["ops"] },
  { id: 926, type: ["design"] },
  { id: 927, type: ["design"] },
  { id: 928, type: ["ops", "design"] },
  { id: 929, type: ["design"] },
  { id: 930, type: ["measure", "delegate"] },
  { id: 931, type: ["ops"] },
  { id: 932, type: ["review"] },
  { id: 933, type: ["design"] },
  { id: 934, type: ["correction", "fix"] },
  { id: 935, type: ["design"] },
  { id: 936, type: ["implement", "review"] },
  { id: 937, type: ["design"] },
  { id: 938, type: ["review", "design"] },
  { id: 939, type: ["design"] },
  { id: 940, type: ["review"] },
  { id: 941, type: ["measure"] },
  { id: 942, type: ["implement", "review", "delegate"] },
  { id: 943, type: ["implement", "review", "ops"] },
  { id: 944, type: ["compact"] },
  { id: 945, type: ["implement", "review", "ops"] },
  { id: 946, type: ["implement", "review", "ops"] },
  { id: 947, type: ["delegate", "review"] },
  { id: 948, type: ["review", "research"] },
  { id: 949, type: ["fix", "implement"] },
  { id: 950, type: ["design", "discuss"] },
  { id: 951, type: ["design", "review"] },
  { id: 952, type: ["design", "review"] },
  { id: 953, type: ["design", "discuss"] },
  { id: 954, type: ["design"] },
  { id: 955, type: ["design", "discuss"] },
  { id: 956, type: ["design"] },
  { id: 957, type: ["design"] },
  { id: 958, type: ["design", "correction"] },
  { id: 959, type: ["design", "implement"] },
  { id: 960, type: ["delegate", "review"] },
  { id: 961, type: ["review"] },
  { id: 962, type: ["design", "fix"] },
  { id: 963, type: ["research", "discuss"] },
  { id: 964, type: ["design"] },
  { id: 965, type: ["design", "delegate"] },
  { id: 966, type: ["delegate", "ops"] },
  { id: 967, type: [] },
  { id: 968, type: ["fix", "ops"] },
  { id: 969, type: ["research"] },
  { id: 970, type: ["implement", "review", "ops"] },
  { id: 971, type: ["implement", "ops"] },
  { id: 972, type: ["implement", "review", "ops"] },
  { id: 973, type: ["design", "implement"] },
  { id: 974, type: ["implement", "fix"] },
  { id: 975, type: ["design", "discuss"] },
  { id: 976, type: ["implement", "review", "ops"] },
  { id: 977, type: ["research", "review"] },
  { id: 978, type: ["design"] },
  { id: 979, type: ["design", "delegate"] },
  { id: 980, type: [] },
  { id: 981, type: ["design"] },
  { id: 982, type: ["implement", "review", "ops"] },
  { id: 983, type: ["review"] },
  { id: 984, type: ["fix", "implement"] },
  { id: 985, type: ["implement", "review", "ops"] },
  { id: 986, type: ["research"] },
  { id: 987, type: ["review", "research"] },
  { id: 988, type: ["research", "discuss"] },
  { id: 989, type: ["review", "measure", "design"] },
  { id: 990, type: ["fix", "design", "correction"] },
  { id: 991, type: ["fix", "ops"] },
  { id: 992, type: ["review", "delegate"] },
  { id: 993, type: ["ops"] },
  { id: 994, type: ["design", "discuss"] },
  { id: 995, type: ["design", "ops"] },
  { id: 996, type: ["research", "review", "ops"] },
  { id: 997, type: ["research"] },
  { id: 998, type: ["ops"] },
  { id: 999, type: ["delegate"] },
  { id: 1000, type: ["review", "measure"] },
  { id: 1001, type: ["fix", "ops"] },
];

export const FLOW_WINDOW_EDGES: readonly FlowEdgeInput[] = [
  { citingId: 901, relation: "extends", citedId: 900 },
  { citingId: 902, relation: "consume", citedId: 900 },
  { citingId: 903, relation: "consume", citedId: 902 },
  { citingId: 904, relation: "consume", citedId: 902 },
  { citingId: 905, relation: "consume", citedId: 904 },
  { citingId: 906, relation: "extends", citedId: 900 },
  { citingId: 910, relation: "extends", citedId: 900 },
  { citingId: 911, relation: "consume", citedId: 905 },
  { citingId: 912, relation: "extends", citedId: 910 },
  { citingId: 913, relation: "extends", citedId: 912 },
  { citingId: 915, relation: "extends", citedId: 914 },
  { citingId: 919, relation: "grounds", citedId: 918 },
  { citingId: 920, relation: "extends", citedId: 919 },
  { citingId: 921, relation: "extends", citedId: 920 },
  { citingId: 922, relation: "extends", citedId: 921 },
  { citingId: 923, relation: "grounds", citedId: 922 },
  { citingId: 924, relation: "consume", citedId: 923 },
  { citingId: 926, relation: "grounds", citedId: 924 },
  { citingId: 927, relation: "extends", citedId: 926 },
  { citingId: 928, relation: "consume", citedId: 925 },
  { citingId: 929, relation: "extends", citedId: 927 },
  { citingId: 930, relation: "grounds", citedId: 929 },
  { citingId: 931, relation: "consume", citedId: 930 },
  { citingId: 932, relation: "consume", citedId: 930 },
  { citingId: 933, relation: "grounds", citedId: 932 },
  { citingId: 935, relation: "extends", citedId: 933 },
  { citingId: 936, relation: "consume", citedId: 930 },
  { citingId: 936, relation: "grounds", citedId: 910 },
  { citingId: 937, relation: "extends", citedId: 935 },
  { citingId: 938, relation: "extends", citedId: 937 },
  { citingId: 939, relation: "extends", citedId: 938 },
  { citingId: 940, relation: "grounds", citedId: 939 },
  { citingId: 941, relation: "refutes", citedId: 935 },
  { citingId: 942, relation: "consume", citedId: 930 },
  { citingId: 942, relation: "grounds", citedId: 935 },
  { citingId: 945, relation: "grounds", citedId: 939 },
  { citingId: 946, relation: "consume", citedId: 945 },
  { citingId: 946, relation: "grounds", citedId: 912 },
  { citingId: 947, relation: "consume", citedId: 946 },
  { citingId: 948, relation: "consume", citedId: 947 },
  { citingId: 949, relation: "consume", citedId: 948 },
  { citingId: 951, relation: "extends", citedId: 950 },
  { citingId: 952, relation: "extends", citedId: 951 },
  { citingId: 953, relation: "extends", citedId: 952 },
  { citingId: 954, relation: "extends", citedId: 953 },
  { citingId: 955, relation: "extends", citedId: 954 },
  { citingId: 957, relation: "extends", citedId: 955 },
  { citingId: 958, relation: "override", citedId: 957 },
  { citingId: 959, relation: "grounds", citedId: 954 },
  { citingId: 959, relation: "grounds", citedId: 958 },
  { citingId: 960, relation: "consume", citedId: 959 },
  { citingId: 961, relation: "consume", citedId: 960 },
  { citingId: 962, relation: "grounds", citedId: 961 },
  { citingId: 964, relation: "grounds", citedId: 963 },
  { citingId: 965, relation: "consume", citedId: 962 },
  { citingId: 965, relation: "grounds", citedId: 959 },
  { citingId: 966, relation: "grounds", citedId: 965 },
  { citingId: 970, relation: "consume", citedId: 966 },
  { citingId: 971, relation: "consume", citedId: 966 },
  { citingId: 971, relation: "grounds", citedId: 964 },
  { citingId: 972, relation: "consume", citedId: 970 },
  { citingId: 973, relation: "grounds", citedId: 972 },
  { citingId: 974, relation: "consume", citedId: 972 },
  { citingId: 974, relation: "grounds", citedId: 958 },
  { citingId: 976, relation: "grounds", citedId: 973 },
  { citingId: 978, relation: "grounds", citedId: 977 },
  { citingId: 979, relation: "extends", citedId: 978 },
  { citingId: 981, relation: "extends", citedId: 979 },
  { citingId: 982, relation: "grounds", citedId: 973 },
  { citingId: 983, relation: "consume", citedId: 982 },
  { citingId: 984, relation: "consume", citedId: 983 },
  { citingId: 985, relation: "consume", citedId: 982 },
  { citingId: 985, relation: "grounds", citedId: 978 },
  { citingId: 989, relation: "grounds", citedId: 978 },
  { citingId: 990, relation: "extends", citedId: 989 },
  { citingId: 991, relation: "consume", citedId: 990 },
  { citingId: 992, relation: "consume", citedId: 989 },
  { citingId: 992, relation: "grounds", citedId: 981 },
  { citingId: 993, relation: "consume", citedId: 991 },
  { citingId: 994, relation: "grounds", citedId: 991 },
  { citingId: 995, relation: "grounds", citedId: 994 },
  { citingId: 996, relation: "consume", citedId: 987 },
  { citingId: 996, relation: "consume", citedId: 992 },
  { citingId: 998, relation: "consume", citedId: 911 },
  { citingId: 998, relation: "consume", citedId: 936 },
  { citingId: 998, relation: "consume", citedId: 942 },
  { citingId: 998, relation: "consume", citedId: 945 },
  { citingId: 998, relation: "consume", citedId: 946 },
  { citingId: 998, relation: "consume", citedId: 949 },
  { citingId: 998, relation: "consume", citedId: 970 },
  { citingId: 998, relation: "consume", citedId: 971 },
  { citingId: 998, relation: "consume", citedId: 972 },
  { citingId: 998, relation: "consume", citedId: 974 },
  { citingId: 998, relation: "consume", citedId: 976 },
  { citingId: 998, relation: "consume", citedId: 982 },
  { citingId: 998, relation: "consume", citedId: 984 },
  { citingId: 998, relation: "consume", citedId: 985 },
  { citingId: 998, relation: "consume", citedId: 989 },
  { citingId: 998, relation: "consume", citedId: 992 },
  { citingId: 998, relation: "consume", citedId: 996 },
  { citingId: 998, relation: "grounds", citedId: 900 },
  { citingId: 998, relation: "grounds", citedId: 935 },
  { citingId: 998, relation: "grounds", citedId: 959 },
  { citingId: 998, relation: "grounds", citedId: 964 },
  { citingId: 998, relation: "grounds", citedId: 973 },
  { citingId: 998, relation: "grounds", citedId: 978 },
  { citingId: 998, relation: "grounds", citedId: 981 },
  { citingId: 998, relation: "grounds", citedId: 990 },
  { citingId: 999, relation: "consume", citedId: 998 },
  { citingId: 1000, relation: "consume", citedId: 999 },
  { citingId: 1001, relation: "consume", citedId: 998 },
  { citingId: 1001, relation: "consume", citedId: 999 },
  { citingId: 1001, relation: "consume", citedId: 1000 },
];
