export const CANONICAL_DIARY_WIRE_FORMAT_EXAMPLE = [
  "===DIARY_V2_BEGIN===",
  "## 工作",
  "**<项目名>**",
  "- <一条第一人称事实> [S1/T1]",
  "  <属于上一条 bullet 的可选续行>",
  "## 人物",
  "- <一条人物相关事实> [S1/T1，T2，S2/T1]",
  "## 反思",
  "- <一条反思> [S1/T1]",
  "===DIARY_V2_END===",
  "===INDEX_HOOK_V1===",
  "<一条非空单行索引钩子>",
].join("\n");

export const CANONICAL_PERSONA_WIRE_FORMAT_EXAMPLE = [
  "===USER_PROFILE_V1_BEGIN===",
  "## 身份与背景",
  "- <一条有依据的特征> [S1/T1]",
  "## 专长与判断力",
  "- <一条有依据的特征> [S1/T1]",
  "## 品味与兴趣",
  "- <一条有依据的特征> [S1/T1]",
  "## 沟通风格",
  "- <一条有依据的特征> [S1/T1]",
  "## 协作偏好",
  "- <一条有依据的特征> [S1/T1]",
  "===USER_PROFILE_V1_END===",
  "===EXPERIENCE_V1_BEGIN===",
  "## 项目",
  "- **<语义化项目名>**：<一句话印象> [S1/T1]",
  "    - 路径：[\"/absolute/path\"]",
  "    - 进度：<当前状态> [S1/T1]",
  "    - 反馈：<协作经验> [S1/T1]",
  "    - [2026-07] <印象事件> [S1/T1]",
  "## 通用",
  "- <跨项目经验> [S1/T1]",
  "===EXPERIENCE_V1_END===",
].join("\n");
