import { LANE_COUPLING_GROUPS, type LaneCheckerResult } from "../../src/shared/lane-checker";

/**
 * A DETERMINISTIC, LOOP-BUILT `LaneCheckerResult` large enough to reproduce
 * the real-run failure the settlement-ergonomics ticket 05 fixes: a
 * `lane_check` render that blew past `WORKER_TOOL_RESULT_MAX_CHARS`
 * (128,100 characters / 1,773 lines, one call, no error recovery — the
 * run's own only checker call).
 *
 * "确定性大 fixture" (the ticket's own words): not a live production
 * snapshot (the suite is HOME-sandboxed and must not touch a real database —
 * see `tests/support/sandbox-home.preload.ts`), and not a three-lane toy
 * either — a toy shape cannot reproduce a cap failure that only shows up at
 * volume. This is generated by plain loops, so it is exactly reproducible
 * across runs while still exercising every report family
 * `renderLaneCheckerReportsPaged`'s paging/aggregation has to handle at
 * scale: many per-lane blocks (reports 1/2/3), a bounded-but-real bypass
 * list (4b), the two FOLDED families (4c time-order violations, stock
 * cross-segment warnings), the two core-capped fact lists (vocabulary
 * conformance, unattributed clusters), several proliferation warnings, and a
 * large uncapped error list (E3/E4/E6 mixed).
 *
 * Every id is a small positive integer with no meaning beyond uniqueness —
 * this is a RENDER-layer fixture (`shared/lane-checker-render.ts`), never run
 * through `checkLanes`, so nothing here needs to satisfy the core's own
 * semantic invariants (a real checker output always would).
 */

const LANE_COUNT = 150;
const BYPASS_CANDIDATE_COUNT = 25;
const TIME_ORDER_VIOLATION_COUNT = 80;
const STOCK_WARNING_COUNT = 80;
const TYPE_VIOLATION_TRUE_COUNT = 30;
const TYPE_VIOLATION_ENTRY_CAP = 20;
const OUT_OF_VOCABULARY_TRUE_COUNT = 30;
const OUT_OF_VOCABULARY_ENTRY_CAP = 20;
const UNATTRIBUTED_CLUSTER_TRUE_COUNT = 25;
const UNATTRIBUTED_CLUSTER_ENTRY_CAP = 20;
const LANE_PROLIFERATION_COUNT = 10;
const E3_ERROR_COUNT = 100;
const E4_ERROR_COUNT = 100;
const E6_ERROR_COUNT = 50;

export function buildLargeLaneCheckerFixture(): LaneCheckerResult {
  const lanes: LaneCheckerResult["lanes"] = Array.from({ length: LANE_COUNT }, (_, index) => {
    const segment = String(1000 + index);
    const tag = "lane-" + index;
    const key = { segment, tag };
    const memberA = 10_000 + index * 2;
    const memberB = memberA + 1;
    return {
      key,
      phases: ["decision" as const],
      members: [{ id: memberA }, { id: memberB }],
      edgeCountsByRelation: { extends: 1, indexes: 1 },
      declaration: { state: "declared" as const, terminus: memberB },
      state: { key, closure: "closed" as const, terminus: memberB },
      citedness: {
        groundsFromNonMembers: [{ citingId: memberA + 5000, citedId: memberA }],
        usedFromNonMembers: [],
        testimonyFromNonMembers: [],
      },
      coverage: { status: "whole" as const, missingTurnIds: [] },
    };
  });

  const components: LaneCheckerResult["components"] = lanes.map((lane) => ({
    key: lane.key,
    componentCount: 1,
    islands: [{ representative: lane.members[0]!.id, memberIds: lane.members.map((m) => m.id) }],
    terminusCitedness: { terminus: lane.members[1]!.id, citedBy: [] },
  }));

  const coupling: LaneCheckerResult["coupling"] = lanes.map((lane) => ({
    key: lane.key,
    groups: LANE_COUPLING_GROUPS.map((relations, groupIndex) => ({
      relations,
      count: groupIndex === 0 ? 2 : groupIndex === 1 ? 0 : 1,
    })),
  }));

  const bypassCandidates: LaneCheckerResult["bypassCandidates"] = Array.from(
    { length: BYPASS_CANDIDATE_COUNT },
    (_, index) => ({
      segment: "1000",
      citingId: 20_000 + index,
      citedId: 19_999,
      relations: ["consume"],
      alternativePath: [20_000 + index, 19_998, 19_999],
    }),
  );

  const timeOrderViolations: LaneCheckerResult["timeOrderViolations"] = Array.from(
    { length: TIME_ORDER_VIOLATION_COUNT },
    (_, index) => ({
      citingId: 30_000 + index,
      citedId: 30_000 + index + 1,
      relation: "extends",
      tags: ["lane-" + (index % LANE_COUNT)],
    }),
  );

  const warnings: LaneCheckerResult["warnings"] = Array.from({ length: STOCK_WARNING_COUNT }, (_, index) => ({
    citingId: 40_000 + index,
    citedId: 40_000 + index - 1,
    tagSet: ["cross-" + index],
    citingSegment: String(2000 + (index % 5)),
    citedSegment: String(2100 + (index % 5)),
  }));

  const typeViolationEntries = Array.from({ length: TYPE_VIOLATION_ENTRY_CAP }, (_, index) => ({
    id: 50_000 + index,
    types: ["legacy-" + index],
    outsideVocabulary: ["legacy-" + index],
  }));

  const outOfVocabularyEntries = Array.from({ length: OUT_OF_VOCABULARY_ENTRY_CAP }, (_, index) => ({
    citingId: 60_000 + index,
    citedId: 60_000 + index - 1,
    relation: "supersedes",
  }));

  const unattributedClusterEntries = Array.from(
    { length: UNATTRIBUTED_CLUSTER_ENTRY_CAP },
    (_, index) => {
      const base = 70_000 + index * 4;
      return {
        turnIds: [base, base + 1, base + 2, base + 3],
        turnCount: 4,
      };
    },
  );

  const laneProliferation: LaneCheckerResult["laneProliferation"] = Array.from(
    { length: LANE_PROLIFERATION_COUNT },
    (_, index) => ({
      segment: String(3000 + index),
      declaredLaneCount: 20 + index,
      memberTurnCount: 100,
      allowance: 5,
      emptyLaneTags: index % 2 === 0 ? ["ghost-" + index] : [],
    }),
  );

  const e3Errors: LaneCheckerResult["errors"] = Array.from({ length: E3_ERROR_COUNT }, (_, index) => ({
    class: "E3" as const,
    anchorId: 80_000 + index,
    id: 80_000 + index,
    types: [] as string[],
    outsideVocabulary: [] as string[],
  }));
  const e4Errors: LaneCheckerResult["errors"] = Array.from({ length: E4_ERROR_COUNT }, (_, index) => ({
    class: "E4" as const,
    anchorId: 81_000 + index,
    citingId: 81_000 + index,
    citedId: 81_000 + index - 1,
    relation: "extends",
    tags: ["lane-" + (index % LANE_COUNT)],
    missing: [{ tag: "lane-" + (index % LANE_COUNT), endpoint: "cited" as const }],
  }));
  const e6Errors: LaneCheckerResult["errors"] = Array.from({ length: E6_ERROR_COUNT }, (_, index) => ({
    class: "E6" as const,
    anchorId: 82_000 + index,
    citingId: 82_000 + index,
    citedId: 82_000 + index - 1,
    relation: "consume",
    tags: [] as string[],
    unsettledSides: ["tail", "head"] as const,
  }));

  return {
    lanes,
    components,
    coupling,
    bypassCandidates,
    timeOrderViolations,
    warnings,
    vocabularyConformance: {
      typeViolations: { count: TYPE_VIOLATION_TRUE_COUNT, entries: typeViolationEntries },
      outOfVocabularyEdges: { count: OUT_OF_VOCABULARY_TRUE_COUNT, entries: outOfVocabularyEntries },
    },
    unattributedClusters: { count: UNATTRIBUTED_CLUSTER_TRUE_COUNT, entries: unattributedClusterEntries },
    laneProliferation,
    errors: [...e3Errors, ...e4Errors, ...e6Errors],
  };
}
