import { LANE_COUPLING_GROUPS, type LaneCheckerResult } from "../../src/shared/lane-checker";

/**
 * A DETERMINISTIC, LOOP-BUILT `LaneCheckerResult` large enough to reproduce
 * the real-run failure the settlement-ergonomics ticket 05 fixes: a
 * `lane_check` render that blew past `WORKER_TOOL_RESULT_MAX_CHARS`
 * (128,100 characters / 1,773 lines, one call, no error recovery — the
 * run's own only checker call).
 *
 * "确定性大 fixture" (the ticket's own words): not a live production
 * snapshot (the suite is HOME-sandboxed and must not touch a real database —
 * see `tests/support/sandbox-home.preload.ts`), and not a three-lane toy
 * either — a toy shape cannot reproduce a cap failure that only shows up at
 * volume. This is generated by plain loops, so it is exactly reproducible
 * across runs while still exercising every report family
 * `renderLaneCheckerReportsPaged`'s paging/aggregation has to handle at
 * scale: many per-lane blocks (reports 1/2/3), a bounded-but-real bypass
 * list (4b), the two FOLDED families (4c time-order violations, stock
 * cross-segment warnings), the two core-capped fact lists (vocabulary
 * conformance, unattributed clusters), several proliferation warnings, and a
 * large uncapped error list (E3/E4/E6 mixed).
 *
 * Every id is a small positive integer with no meaning beyond uniqueness —
 * this is a RENDER-layer fixture (`shared/lane-checker-render.ts`), never run
 * through `checkLanes`, so nothing here needs to satisfy the core's own
 * semantic invariants (a real checker output always would).
 */

// lane-state-retirement ticket 01 RAISED this from 150. Report 1 lost its
// declaration line and report 2 its closed-terminus line — one line per lane
// each — so the 150-lane fixture's unpaged render fell to ~89K and stopped
// exceeding `WORKER_TOOL_RESULT_MAX_CHARS`, which is the premise the paging
// tests stand on ("the OLD unbounded render already exceeds the cap on this
// fixture"). 250 puts it back at ~126K, the order of magnitude of the
// measured 128,100-character failure this fixture exists to reproduce.
// main-agent-edges ticket 02 took ANOTHER two families out of the render —
// report 1's `cited from outside:` line (one per lane) and the whole
// index-granularity block — so the same fixture fell back under the cap. 400
// lanes restores the premise, at the same order of magnitude as the measured
// 128,100-character failure this fixture exists to reproduce.
const LANE_COUNT = 400;
const BYPASS_CANDIDATE_COUNT = 25;
const TIME_ORDER_VIOLATION_COUNT = 80;
const STOCK_WARNING_COUNT = 80;
const TYPE_VIOLATION_TRUE_COUNT = 30;
const TYPE_VIOLATION_ENTRY_CAP = 20;
const OUT_OF_VOCABULARY_TRUE_COUNT = 30;
const OUT_OF_VOCABULARY_ENTRY_CAP = 20;
const UNATTRIBUTED_CLUSTER_TRUE_COUNT = 25;
const UNATTRIBUTED_CLUSTER_ENTRY_CAP = 20;
const LANE_PROLIFERATION_COUNT = 10;
const E3_ERROR_COUNT = 100;
const E4_ERROR_COUNT = 100;
const E6_ERROR_COUNT = 50;

export function buildLargeLaneCheckerFixture(): LaneCheckerResult {
  const lanes: LaneCheckerResult["lanes"] = Array.from({ length: LANE_COUNT }, (_, index) => {
    const segment = String(1000 + index);
    const tag = "lane-" + index;
    const key = { segment, tag };
    const memberA = 10_000 + index * 2;
    const memberB = memberA + 1;
    return {
      key,
      phases: ["decision" as const],
      members: [{ id: memberA }, { id: memberB }],
      edgeCountsByRelation: { extends: 1, indexes: 1 },
      coverage: { status: "whole" as const, missingTurnIds: [] },
    };
  });

  const components: LaneCheckerResult["components"] = lanes.map((lane) => ({
    key: lane.key,
    componentCount: 1,
    islands: [{ representative: lane.members[0]!.id, memberIds: lane.members.map((m) => m.id) }],
  }));

  const coupling: LaneCheckerResult["coupling"] = lanes.map((lane) => ({
    key: lane.key,
    groups: LANE_COUPLING_GROUPS.map((relations, groupIndex) => ({
      relations,
      count: groupIndex === 0 ? 2 : groupIndex === 1 ? 0 : 1,
    })),
  }));

  const bypassCandidates: LaneCheckerResult["bypassCandidates"] = Array.from(
    { length: BYPASS_CANDIDATE_COUNT },
    (_, index) => ({
      segment: "1000",
      citingId: 20_000 + index,
      citedId: 19_999,
      relations: ["consume"],
      alternativePath: [20_000 + index, 19_998, 19_999],
    }),
  );

  const timeOrderViolations: LaneCheckerResult["timeOrderViolations"] = Array.from(
    { length: TIME_ORDER_VIOLATION_COUNT },
    (_, index) => ({
      citingId: 30_000 + index,
      citedId: 30_000 + index + 1,
      relation: "extends",
      tags: ["lane-" + (index % LANE_COUNT)],
    }),
  );

  const warnings: LaneCheckerResult["warnings"] = Array.from({ length: STOCK_WARNING_COUNT }, (_, index) => ({
    citingId: 40_000 + index,
    citedId: 40_000 + index - 1,
    tagSet: ["cross-" + index],
    citingSegment: String(2000 + (index % 5)),
    citedSegment: String(2100 + (index % 5)),
  }));

  const typeViolationEntries = Array.from({ length: TYPE_VIOLATION_ENTRY_CAP }, (_, index) => ({
    id: 50_000 + index,
    types: ["legacy-" + index],
    outsideVocabulary: ["legacy-" + index],
  }));

  const outOfVocabularyEntries = Array.from({ length: OUT_OF_VOCABULARY_ENTRY_CAP }, (_, index) => ({
    citingId: 60_000 + index,
    citedId: 60_000 + index - 1,
    relation: "supersedes",
  }));

  const unattributedClusterEntries = Array.from(
    { length: UNATTRIBUTED_CLUSTER_ENTRY_CAP },
    (_, index) => {
      const base = 70_000 + index * 4;
      return {
        turnIds: [base, base + 1, base + 2, base + 3],
        turnCount: 4,
      };
    },
  );

  const laneProliferation: LaneCheckerResult["laneProliferation"] = Array.from(
    { length: LANE_PROLIFERATION_COUNT },
    (_, index) => ({
      segment: String(3000 + index),
      declaredLaneCount: 20 + index,
      memberTurnCount: 100,
      allowance: 5,
      emptyLaneTags: index % 2 === 0 ? ["ghost-" + index] : [],
    }),
  );

  const e3Errors: LaneCheckerResult["errors"] = Array.from({ length: E3_ERROR_COUNT }, (_, index) => ({
    class: "E3" as const,
    anchorId: 80_000 + index,
    id: 80_000 + index,
    types: [] as string[],
    outsideVocabulary: [] as string[],
  }));
  const e4Errors: LaneCheckerResult["errors"] = Array.from({ length: E4_ERROR_COUNT }, (_, index) => ({
    class: "E4" as const,
    anchorId: 81_000 + index,
    citingId: 81_000 + index,
    citedId: 81_000 + index - 1,
    relation: "extends",
    tags: ["lane-" + (index % LANE_COUNT)],
    missing: [{ tag: "lane-" + (index % LANE_COUNT), endpoint: "cited" as const }],
  }));
  const e6Errors: LaneCheckerResult["errors"] = Array.from({ length: E6_ERROR_COUNT }, (_, index) => ({
    class: "E6" as const,
    anchorId: 82_000 + index,
    citingId: 82_000 + index,
    citedId: 82_000 + index - 1,
    relation: "consume",
    tags: [] as string[],
    unsettledSides: ["tail", "head"] as const,
  }));

  return {
    lanes,
    components,
    coupling,
    bypassCandidates,
    timeOrderViolations,
    warnings,
    vocabularyConformance: {
      typeViolations: { count: TYPE_VIOLATION_TRUE_COUNT, entries: typeViolationEntries },
      outOfVocabularyEdges: { count: OUT_OF_VOCABULARY_TRUE_COUNT, entries: outOfVocabularyEntries },
    },
    unattributedClusters: { count: UNATTRIBUTED_CLUSTER_TRUE_COUNT, entries: unattributedClusterEntries },
    laneProliferation,
    errors: [...e3Errors, ...e4Errors, ...e6Errors],
  };
}

/**
 * `lane_check`'s THIRD layer (settlement-ergonomics ticket 06, spec D3 item
 * 3): `scope: "actionable"` vs `"all"`. A DEDICATED, hand-built fixture — NOT
 * `buildLargeLaneCheckerFixture` above, which is sized for the PAGING cap and
 * gives no control over which ids sit inside a window.
 *
 * Every DECIDABLE report family below carries exactly TWO entries, one whose
 * covered turns are entirely inside `actionableTurnIds` and one entirely outside
 * it, so a test can assert the two scopes render DIFFERENT text PER FAMILY —
 * this is the ticket's own inertness risk: a fixture whose findings are all
 * in-window would make `actionable`/`all` render identically and every
 * mutation on the filter would be inert without anyone noticing.
 *
 * Three families additionally carry an UNDECIDABLE entry, the "cannot decide
 * honestly, leave it in actionable" arm `projectLaneCheckerResultByScope`
 * documents:
 *   - `coupling` — a key naming no reported lane at all.
 *   - `laneProliferation` — a segment with no reported lane at all.
 *   - `unattributedClusters` — a cluster whose shown `turnIds` sample is
 *     truncated below its own true `turnCount`, with no window hit among the
 *     turns actually shown (the OTHER kind of undecidable case: a negative
 *     result from an incomplete sample).
 */
const SCOPE_FIXTURE_LANE_IN_KEY = { segment: "1", tag: "in-lane" };
const SCOPE_FIXTURE_LANE_OUT_KEY = { segment: "2", tag: "out-lane" };

const SCOPE_WHOLE_COVERAGE = { status: "whole" as const, missingTurnIds: [] };

function scopeFixtureLane(
  key: { segment: string; tag: string },
  memberId: number,
): LaneCheckerResult["lanes"][number] {
  return {
    key,
    phases: [],
    members: [{ id: memberId }],
    edgeCountsByRelation: {},
    coverage: SCOPE_WHOLE_COVERAGE,
  };
}

export function buildScopeFixture(): {
  result: LaneCheckerResult;
  actionableTurnIds: ReadonlySet<number>;
} {
  const actionableTurnIds = new Set<number>([
    101, // errors (in)
    110, // lanes/components/coupling (in)
    120, 121, 122, // bypassCandidates (in)
    130, 131, // timeOrderViolations (in)
    140, 141, // warnings / stock cross-segment (in)
    150, 151, // outOfVocabularyEdges (in)
    160, 161, 162, 163, // unattributedClusters (in, fully shown)
  ]);

  const laneIn = scopeFixtureLane(SCOPE_FIXTURE_LANE_IN_KEY, 110);
  const laneOut = scopeFixtureLane(SCOPE_FIXTURE_LANE_OUT_KEY, 210);
  const lanes: LaneCheckerResult["lanes"] = [laneIn, laneOut];

  const components: LaneCheckerResult["components"] = [
    {
      key: laneIn.key,
      componentCount: 1,
      islands: [{ representative: 110, memberIds: [110] }],
    },
    {
      key: laneOut.key,
      componentCount: 1,
      islands: [{ representative: 210, memberIds: [210] }],
    },
  ];

  const couplingGroups = LANE_COUPLING_GROUPS.map((relations) => ({ relations, count: 0 }));
  const coupling: LaneCheckerResult["coupling"] = [
    { key: laneIn.key, groups: couplingGroups },
    { key: laneOut.key, groups: couplingGroups },
    // UNDECIDABLE: no entry in `lanes` above carries this key at all.
    { key: { segment: "3", tag: "orphan-coupling" }, groups: couplingGroups },
  ];

  const bypassCandidates: LaneCheckerResult["bypassCandidates"] = [
    { segment: "1", citingId: 120, citedId: 121, relations: ["consume"], alternativePath: [120, 122, 121] },
    { segment: "2", citingId: 220, citedId: 221, relations: ["consume"], alternativePath: [220, 222, 221] },
  ];

  const timeOrderViolations: LaneCheckerResult["timeOrderViolations"] = [
    { citingId: 130, citedId: 131, relation: "extends", tags: ["in-lane"] },
    { citingId: 230, citedId: 231, relation: "extends", tags: ["out-lane"] },
  ];

  const warnings: LaneCheckerResult["warnings"] = [
    { citingId: 140, citedId: 141, tagSet: ["cross-in"], citingSegment: "1", citedSegment: "5" },
    { citingId: 240, citedId: 241, tagSet: ["cross-out"], citingSegment: "2", citedSegment: "6" },
  ];

  const outOfVocabularyEntries = [
    { citingId: 150, citedId: 151, relation: "supersedes" },
    { citingId: 250, citedId: 251, relation: "supersedes" },
  ];

  const unattributedClusterEntries: LaneCheckerResult["unattributedClusters"]["entries"] = [
    { turnIds: [160, 161, 162, 163], turnCount: 4 }, // fully shown, in window -> decidably kept
    { turnIds: [260, 261, 262, 263], turnCount: 4 }, // fully shown, out of window -> decidably dropped
    { turnIds: [300, 301], turnCount: 50 }, // truncated, no hit in the shown sample -> undecidable, kept
  ];

  const laneProliferation: LaneCheckerResult["laneProliferation"] = [
    { segment: "1", declaredLaneCount: 5, memberTurnCount: 10, allowance: 1 }, // matches laneIn -> decidably kept
    { segment: "2", declaredLaneCount: 5, memberTurnCount: 10, allowance: 1 }, // matches laneOut -> decidably dropped
    { segment: "9", declaredLaneCount: 5, memberTurnCount: 10, allowance: 1 }, // no reported lane at all -> undecidable, kept
  ];

  const errors: LaneCheckerResult["errors"] = [
    { class: "E3", anchorId: 101, id: 101, types: [], outsideVocabulary: [] },
    { class: "E3", anchorId: 201, id: 201, types: [], outsideVocabulary: [] },
  ];

  const result: LaneCheckerResult = {
    lanes,
    components,
    coupling,
    bypassCandidates,
    timeOrderViolations,
    warnings,
    vocabularyConformance: {
      typeViolations: { count: 0, entries: [] },
      outOfVocabularyEdges: { count: outOfVocabularyEntries.length, entries: outOfVocabularyEntries },
    },
    unattributedClusters: { count: unattributedClusterEntries.length, entries: unattributedClusterEntries },
    laneProliferation,
    errors,
  };

  return { result, actionableTurnIds };
}
